// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aitcwrjhsmpzzvquzvws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpdGN3cmpoc21wenp2cXV6dndzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMTExMjIsImV4cCI6MjA2ODg4NzEyMn0.6sH4jO1To3W7c1zHAs59A-pyl7dZtkTwGZaJ6xiR6O8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});